# Generated by Django 2.2.6 on 2019-10-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20191006_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='id',
        ),
        migrations.AlterField(
            model_name='bank',
            name='ifsc_code',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
